# Loki Minimal Configuration (SingleBinary Mode)
# GDPR Compliant: 7-day retention

# Deployment mode
deploymentMode: SingleBinary

# Single binary configuration
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 50Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi

# Loki configuration
loki:
  auth_enabled: false
  
  commonConfig:
    replication_factor: 1
  
  storage:
    type: 'filesystem'
  
  schemaConfig:
    configs:
    - from: "2024-01-01"
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: loki_index_
        period: 24h
  
  # Retention and rate limits configuration
  limits_config:
    retention_period: 168h  # 7 days for GDPR
    ingestion_rate_mb: 16  # Increase from 4MB/s to 16MB/s
    ingestion_burst_size_mb: 32  # Increase burst size
    per_stream_rate_limit: 8MB  # Per stream limit
    per_stream_rate_limit_burst: 16MB  # Per stream burst

compactor:
  retention_enabled: true
  delete_request_store: filesystem

# Monitoring
monitoring:
  selfMonitoring:
    enabled: false
  lokiCanary:
    enabled: true

# Test disabled
test:
  enabled: false

# Backend and read/write components (disabled for SingleBinary)
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
