apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: monitoring  # Change to your namespace
  labels:
    app: myapp
    version: v1.0.0
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: myapp
